service: configurator
provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
functions:
  configFetcher:
    handler: fetcher/fetcher.fetch
    memorySize: 128
    description: Submit candidate information and starts interview process.
    events:
      - sns: config
  snsTrigger:
    handler: trigger/trigger.trigger
    memorySize: 128
    description: Triggers Config SNS
    events:
      - http:
          path: config
          method: post
      - sns: config