service: configurator
provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
functions:
  configFetcher:
    handler: fetcher/fetcher.fetch
    memorySize: 128
    description: Fetches config
    events:
      - sns: config